smart:
  dataMachineId: 2
  async: true
  log:
    rpclog: true
    apilog: true

server:
  port: 20011
  
seata:
  tx-service-group: smartcloud_tx_group
  enable-auto-data-source-proxy: false
  service:
    grouplist: 
      smartcloud: 127.0.0.1:8091
    vgroup-mapping: 
      smartcloud_tx_group: smartcloud

spring:
  application:
    name: mallServiceOrder
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 1000
        min-idle: 0
        max-idle: 100
        max-wait: 10000ms
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: guest
    password: guest